"""init

Revision ID: 3438e8a3f63a
Revises: 
Create Date: 2026-03-07 21:19:09.445612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3438e8a3f63a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('academic_leave_orders',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('leave_start', sa.Date(), nullable=True),
    sa.Column('leave_end', sa.Date(), nullable=True),
    sa.Column('leave_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('deans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('faculty_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('directions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('study_duration_years', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollment_orders',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('education_form', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('expulsion_orders',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('expulsion_date', sa.Date(), nullable=True),
    sa.Column('expulsion_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('next_course_orders',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('from_course', sa.Integer(), nullable=True),
    sa.Column('to_course', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('curriculums',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('direction_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['direction_id'], ['directions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('direction_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['direction_id'], ['directions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfer_direction_orders',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('from_direction_id', sa.UUID(), nullable=True),
    sa.Column('to_direction_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['from_direction_id'], ['directions.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['to_direction_id'], ['directions.id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('disciplines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.Column('control_type', sa.String(), nullable=False),
    sa.Column('curriculum_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('patronymic', sa.String(), nullable=True),
    sa.Column('study_book_number', sa.Integer(), nullable=False),
    sa.Column('enrollment_date', sa.Date(), nullable=True),
    sa.Column('expulsion_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_students')
    op.drop_table('students')
    op.drop_table('disciplines')
    op.drop_table('transfer_direction_orders')
    op.drop_table('groups')
    op.drop_table('curriculums')
    op.drop_table('next_course_orders')
    op.drop_table('expulsion_orders')
    op.drop_table('enrollment_orders')
    op.drop_table('directions')
    op.drop_table('deans')
    op.drop_table('academic_leave_orders')
    op.drop_table('orders')
    op.drop_table('faculties')
    # ### end Alembic commands ###
