from .faculty import Faculty
from .direction import Direction
from .student import Student
from .group import Group
from .academic_leave_order import AcademicLeaveOrder
from .curriculum import Curriculum
from .dean import Dean
from .discipline import Discipline
from .enrollment_order import EnrollmentOrder
from .expulsion_order import ExpulsionOrder
from .order import Order
from .order_student import OrderStudent
from .next_course_order import NextCourseOrder
from .transfer_direction_order import TransferDirectionOrder
